name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["9.6", "9.8"]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "latest"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', 'cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-ghc${{ matrix.ghc }}-
      - run: cabal update
      - run: cabal build all
      - run: cabal test all
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.19.0.1"
          pattern: |
            src/**/*.hs
            app/**/*.hs
            test/**/*.hs
      - uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.10"
      - uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "app/", "test/"]'
          fail-on: warning
